### ISSUE TITLE
ja/typescript/54a7f5e8734c14fa7d0a8d6777c5b5ac6fa8ca44/66

### ISSUE THREAD

**Issue by mt-hara** [runebookdev/runebook#180]
> <code>tsconfig.json</code> files have a new top-level property, <code>references</code>. It&rsquo;s an array of objects that specifies projects to reference:

<code>tsconfig.json</code> ファイルには、新しい最上位のプロパティである <code>references</code> があります。これは、参照するプロジェクトを指定するオブジェクトの配列です。

**Comment by runebookdev** [comment]
Invalid title.
