### ISSUE TITLE
ko/docs/php/5c5fbd6f5af3e2f16ed69ac3c91e4167f177cd8d/a4

### ISSUE THREAD

**Issue by JaeHyeokSim** [runebookdev/runebook#399]
> Returns <strong><code>true</code></strong> on success or <strong><code>false</code></strong> on failure.

성공하면 <strong> <code>true</code> </strong> 를, 실패하면 <strong>false</strong> 를 반환 <strong>

**Comment by runebookdev** [comment]
duplicate #400

Thanks for your feedback.
