### ISSUE TITLE
ja/docs/mariadb/e7fbd05c0b280debff7c60b6ca3b37813444c1b7/de

### ISSUE THREAD

**Issue by tunara** [runebookdev/runebook#409]
> The <code>mysql.proc</code> table contains information about <a href="../stored-procedures/index">stored procedures</a> and <a href="../stored-functions/index">stored functions</a>. It contains similar information to that stored in the <a href="../information-schema-routines-table/index">INFORMATION SCHEMA.ROUTINES</a> table.

<code>mysql.proc</code> の表は、<a href="../stored-procedures/index">、ストアド・プロシージャ</a>と<a href="../stored-functions/index">ストアド・ファンクション</a>についての情報を含んでいます。これには、<a href="../information-schema-routines-table/index">INFORMATION SCHEMA.ROUTINES</a>テーブルに格納されている情報と同様の情報が含まれています。

**Comment by runebookdev** [comment]
Invalid title.
