### ISSUE TITLE
ko/docs/sequelize/a6e18661df62cf03ad1b8c1dfaac6d64093d6a9e/eb

### ISSUE THREAD

**Issue by musaepal** [runebookdev/runebook#435]
> In cases where you don't need to access the metadata you can pass in a query type to tell sequelize how to format the results. For example, for a simple select query you could do:

메타 데이터에 액세스 할 필요가없는 경우 쿼리 형식을 전달하여 결과의 ​​형식을 지정하는 방법을 시퀀스에 전달할 수 있습니다. 예를 들어 간단한 선택 쿼리의 경우 다음을 수행 할 수 있습니다.

**Comment by runebookdev** [comment]
thanks!
