### ISSUE TITLE
ja/docs/julia/7ac4008d58382151203baf7753fcd45089959029/4b

### ISSUE THREAD

**Issue by pooneil68** [runebookdev/runebook#694]
> Julia values are not copied when passed to a function. If a function modifies an array, the changes will be visible in the caller.

Juliaの値は関数に渡されてもコピーされません。関数が配列を変更した場合、その変更は呼び出し元に表示されます。

**Comment by Palmerim** [comment]
Os valores de Julia não são copiados quando passados ​​para uma função. Se uma função modificar um array, as alterações serão visíveis no chamador.
